/**
 * Bundle `src/` into `dist/`.
 *
 * Three outputs, all self-contained: a readable IIFE that defines the global
 * `Autograder`, a minified IIFE for the deployed page, and an ES module for
 * tooling. Assertions stay live in every one of them (see `src/assert.ts`).
 */

import { build } from "esbuild";
import type { BuildOptions } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";

const package_json = JSON.parse(
  await readFile(new URL("./package.json", import.meta.url), "utf8"),
) as { version: string };

// Version only, no build date: a date would make every rebuild produce a diff
// even when src/ has not changed, which defeats any "is dist/ stale?" check.
const banner = `/*! autograder v${package_json.version} */`;

const shared: BuildOptions = {
  entryPoints: ["src/index.ts"],
  bundle: true,
  target: ["es2021"],
  sourcemap: true,
  banner: { js: banner },
  logLevel: "info",
};

await mkdir("dist", { recursive: true });

await build({
  ...shared, format: "iife", globalName: "Autograder", outfile: "dist/autograder.js",
});
await build({
  ...shared, format: "iife", globalName: "Autograder",
  outfile: "dist/autograder.min.js", minify: true,
});
await build({ ...shared, format: "esm", outfile: "dist/autograder.esm.js" });

// dist/ is gitignored, so anyone who finds it locally needs to know where it
// came from and that editing it is pointless.
await writeFile("dist/README.md",
  "# dist/\n\nGenerated by `npm run build` from `src/`, and gitignored. The " +
  "GitHub Pages workflow rebuilds it on every push. Do not edit these files by hand.\n");

console.log("built dist/autograder.js, dist/autograder.min.js, dist/autograder.esm.js");
